AI-ICCBS/AI_ICCBS_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name="accounts"
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name="profile"),
    #Django Auth 
    path(
        'login',
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name='login',
        ),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
 ]

AI-ICCBS/AI_ICCBS_website/apps/blog/urls.py
from . import views
from django.urls import path



app_name = "blog"
urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

AI-ICCBS/AI_ICCBS_website/apps/contact/urls.py
from django.urls import path

from .views import contact

app_name = "contact"
urlpatterns = [
    path("", contact, name="contact")
]

AI-ICCBS/AI_ICCBS_website/apps/ticketApp/urls.py
from django.urls import path
from . import views

app_name = "ticketApp"
urlpatterns = [
    path('', views.ICCBSITticketstatus, name='ICCBSITticketstatus'),
    path('ticket/<int:ticket_id>', views.ticket_by_id, name='ticket_by_id'),
]

AI-ICCBS/AI_ICCBS_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.auth.models import User


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AI_ICCBS_website.apps.public.urls')),
    path('accounts/', include('AI_ICCBS_website.apps.accounts.urls')),
    path('contact/', include('AI_ICCBS_website.apps.contact.urls')),
    path('blog/', include('AI_ICCBS_website.apps.blog.urls')),   
    path('ckeditor/', include('ckeditor_uploader.urls')), 
    path('ticketApp/', include("AI_ICCBS_website.apps.ticketApp.urls")),
]   

if settings.DEBUG:
       urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 


 
  

AI-ICCBS/AI_ICCBS_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User  


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

# Create your models here.
class UserProfile(models.Model):
    #owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

   #settings
    is_full_name_displayed = models.BooleanField(default=True)

#details
bio = models.CharField(max_length=500, blank=True, null=True)
website = models.URLField(max_length=200, blank=True, null=True) 
persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
interests = models.ManyToManyField(UserInterest, blank=True)

AI-ICCBS/AI_ICCBS_website/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from ckeditor_uploader.fields import RichTextUploadingField

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = RichTextUploadingField(blank=True,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0) 

    class Meta:
        ordering = ['-created_on']
    def __str__(self):
        return self.title
    

AI-ICCBS/AI_ICCBS_website/apps/contact/models.py
from django.db import models

# Create your models here.

AI-ICCBS/AI_ICCBS_website/apps/ticketApp/models.py
from django.db import models
from django.contrib.auth.models import User

class TicketStatus(models.TextChoices):
 TO_DO = 'To Do'
 IN_PROGRESS = 'In Progress'
 IN_REVIEW = 'In Review'
 DONE = 'Done'

class Ticket(models.Model):
 title = models.CharField(max_length=100)
 assignee = models.ForeignKey(User, null=True, blank = True, on_delete=models.CASCADE)
 status = models.CharField(max_length=25, choices=TicketStatus.choices, default=TicketStatus.TO_DO)
 description = models.TextField()
 created_at = models.DateTimeField('created at', auto_now_add=True)
 updated_at = models.DateTimeField('updated at', auto_now=True)

AI-ICCBS/AI_ICCBS_website/apps/contact/forms.py
from django import forms
from django import forms

class ContactForm(forms.Form):
    name    = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : "Name"}))
    email   = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : "Email"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : "Message"}))

AI-ICCBS/AI_ICCBS_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class ProfileView(LoginRequiredMixin, TemplateView):
   template_name = 'accounts/profile.html'
      

AI-ICCBS/AI_ICCBS_website/apps/blog/views.py
from django.views import generic
from .models import Post

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog.html'
    paginate_by = 3

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

AI-ICCBS/AI_ICCBS_website/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail

from AI_ICCBS_website import settings

from .forms import ContactForm

def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
         form = ContactForm()
    elif  request.method == "POST":
          form = ContactForm(request.POST)

          if form.is_valid():
              name = bleach.clean(form.cleaned_data["name"])
              email = bleach.clean(form.cleaned_data["email"])
              message = bleach.clean(form.cleaned_data["message"])
              send_mail(
                
                    f"{name} sent an email", message, email, [settings.DEFAULT_FROM_EMAIL]
                )

              # Use a new form to clean out the old data and render a sucess message
              return render(
                
                request, 'contact.html', {"form": form, "success": True}
                )
    else:
          raise NotImplementedError
    

    return render(request, 'contact.html', {"form": form})

    
    

    

AI-ICCBS/AI_ICCBS_website/apps/ticketApp/views.py
from django.shortcuts import render
from .models import Ticket
from django.http import HttpResponse

def ICCBSITticketstatus(request:HttpResponse):
 tickets = Ticket.objects.order_by('-created_at')[:25]
 return render(request,'ICCBSITticketstatus.html', {'tickets': tickets})

def ticket_by_id(request:HttpResponse, ticket_id):
 ticket = Ticket.objects.get(pk=ticket_id)
 return render(request, 'ticket_by_id.html', {'ticket':ticket})

 

AI-ICCBS/AI_ICCBS_website/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class ProfileView(LoginRequiredMixin, TemplateView):
   template_name = 'accounts/profile.html'

AI-ICCBS/AI_ICCBS_website/apps/blog/templates/blog.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:blog' as blog_url %}">ICCBS Writers</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Deep Learning</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Machine Learning</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">GPU Cloud</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/AICCBS.png' %}" alt="First slide">
            <div class="carousel-caption d-none d-md-block", style="text-align: center; color:#f00000">
                <h1><strong>TECHNOLOGY PARK</strong></h1>
                <p><strong>Business startup ventures from different sectors</strong></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/deep.png' %}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block", style="text-align: center; color:#f00000">
                <h1><strong>TRAIN YOUR TENSORFLOW MODEL</strong></h1>
                <p><strong>utilize ICCBS GPUs with ML Tools</strong></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/GRAFANA_ICCBS.png' %}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block", style="text-align: center ; color:#f00000">
                <h1><strong>EXPERIENCE ICCBS-GPU INSTRUMENTATION</strong></h1>
                <p><strong>Monitoring, Logging, Versioning, Emailing & More!</strong></p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
        h1 {
        display: block;
        font-size: 5em;
        margin-top: 0.57em;
        margin-bottom: 0.1em;
        margin-left: 0;
        margin-right: 0;
        font-weight: bold;
}

    </style>

        {% endblock %}



        <div class="container">
            <div class="row">
              <div class="col-md-4">
                <div class="card card-1">
                  <h3>Write for Us!</h3>
                  <p>we invite you to write for us about different topics. Your texts can be published in our blogs or in any other format of our web page .</p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="card card-2">
                  <h3>Test our ready AI Components</h3>
                  <p>Python, Anaconda, Tensorflow, Spyder, Matlab, & much more... ready to go.</p>
                </div>
              </div>
              <div class="col-md-4">
                <div class="card card-3">
                  <h3>Our Objective</h3>
                  <p>To provide a common platform for growth-oriented technology entrepreneurs to access resources, mentorship, and space to start and grow their ventures and to graduate from incubation space into commercial space in the Pakistan Industry.</p>
                </div>
              </div>
            </div>
          </div>
<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<style>
body{
    font-family: 'Nunito', sans-serif;
    padding: 50px;
  }
  .card{
      border-radius: 4px;
      background: #fff;
      box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
        transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
    padding: 14px 80px 18px 36px;
    cursor: pointer;
  }
  
  .card:hover{
       transform: scale(1.05);
    box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
  }
  
  .card h3{
    font-weight: 600;
  }
  
  .card img{
    position: absolute;
    top: 20px;
    right: 15px;
    max-height: 120px;
  }
  
  .card-1{
    background-image: url(https://ionicframework.com/img/getting-started/ionic-native-card.png);
        background-repeat: no-repeat;
      background-position: right;
      background-size: 80px;
      background-color: #68a4f1;
  }
  
  .card-2{
     background-image: url(https://ionicframework.com/img/getting-started/components-card.png);
        background-repeat: no-repeat;
      background-position: right;
      background-size: 80px;
      background-color:#68a4f1;
  }
  
  .card-3{
     background-image: url(https://ionicframework.com/img/getting-started/theming-card.png);
        background-repeat: no-repeat;
      background-position: right;
      background-size: 80px;
      background-color: #68a4f1;
  }
  
  @media(max-width: 990px){
    .card{
      margin: 20px;
    }
  } 
</style>
  
  
<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> AI Datacenter in ICCBS offers Opportunities for scientific and technological
            endeavors. We offer cloud services with high end processors and memory
            for fast CPU and GPU rendering.</p>
        <a href="http://172.16.2.37/"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>
</html>





<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to AI-ICCBS Blog Site</h3>
                    <p class="text-light">We Love like to know more about artificial intelligence..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|safe|slice:":200" }}</p>
                    <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
            {% block sidebar %}  {% endblock sidebar %}
        </div>
    </div>
    
    {% if is_paginated %}
    <nav aria-label="Page navigation conatiner"></nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
      {% endif %}
      {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
  
      {% endif %}
    </ul>
    </nav>
  </div>
  {% endif %}

  
    <div class="container">
        <div class="row">
          <div class="col-md-8 card mb-4  mt-3 center  top">
            <div class="card-body">
              <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
              <body>ICCBS</body>
            </div>
        </div>
         
      </div>
    </div>
    


<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Django Central</p>
  </footer>

AI-ICCBS/AI_ICCBS_website/apps/blog/templates/post_detail.html
{% block content %}

<!DOCTYPE html>
<html>

    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4  mt-3 left  top">
                <div class="card-body">
                    <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
                    <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
                    <p class="card-text ">{{ post.content | safe }}</p>
                </div>
            </div>
            


</html>
{% endblock content %}

AI-ICCBS/AI_ICCBS_website/apps/ticketApp/templates/ICCBSITtickets.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Tickets{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
  <div class="header">
    <strong><a class="logo">ICCBS IT-HELPDESK TICKETS</a></strong>
    <div class="header-right">
      <a href="{% url 'ICCBSITticketstatus:ICCBSITticketstatus' as ICCBSITticketstatus_url %}" class=sel></a>
      <a href="/admin/" class=sel>ADMINISTRATOR LOGIN</a>
    </div>
  </div>
   <div id="body">
    <style>.header {
        overflow: hidden;
        background-color: #66aaf8;
        padding: 20px 10px;
        min-width: 200px;
        box-shadow: 0 0 20px rgba(255, 2, 2, 0.15);
      }
      
      .styled-table thead tr {
      background-color: #f87979;
      color: #ffffff;
      text-align: left;
  }
  
      </style>
      
   {% block content %}{% endblock %}
  </div>
</body>
</html>

AI-ICCBS/AI_ICCBS_website/templates/about.html
{% extends 'base.html'%}

{% block title %}About{% endblock %}
{% block content %}

<h1>
    Who v R
</h1>

{% endblock %}

AI-ICCBS/AI_ICCBS_website/templates/blog.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html>

    <head>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        {% endblock %}



<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:blog' as blog_url %}">ICCBS Writers</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Deep Learning</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Machine Learning</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">GPU Cloud</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> AI Datacenter in ICCBS offers Opportunities for scientific and technological
            endeavors. We offer cloud services with high end processors and memory
            for fast CPU and GPU rendering</p>
        <a href="/home/node-1/Documents/#GIT"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

</body>



</html>


  <header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
            {% block sidebar %}  {% endblock sidebar %}
        </div>
    </div>
    

    

    <div class="container">
        <div class="row">
          <div class="col-md-8 card mb-4  mt-3 left  top">
            <div class="card-body">
              <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
              <body>ICCBS</body>
            </div>
        </div>
         
      </div>
    </div>
    
    

<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Django Central</p>
  </footer>

AI-ICCBS/AI_ICCBS_website/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}
{% url 'blog:blog' as blog_url %}
{% url 'accounts:profile' as profile_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}


<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">

        <a class="navbar-brand js-scroll-trigger" href="{index_url}">AIC PORTAL</a>
        <button class="navbar-toggler navbar-togler-right text-uppercase font-weight-bold ai-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3  js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3  js-scroll-trigger {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == blog_url %}active{% endif %}" href="{{ blog_url }}">Blogs</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">profile</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == logout_url %}active{% endif %}" href="{{ logout_url }}">LOGOUT</a></li>
                {% else %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == login_url %}active{% endif %}" href="{{ login_url }}">LOGIN</a></li>
                {% endif %}
                
            </ul>
        </div>
    </div>
</nav>